### PR TITLE
Move JSON value text to its own, earlier section

### PR DESCRIPTION
**Pull request by glyn**
The text will be adjusted in a future PR.

### CODE REVIEW

**Comment by cabo** [comment]
This github bug is slowing me down a bit:

```
error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data) (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `A948:495D:168775B:16D992A:63750568` when reporting this issue."))))
```

**Review by cabo — APPROVED** [review]
Thanks!

**Comment by glyn** [comment]
> This github bug is slowing me down a bit:
> 
> ```
> error in process filter: HTTP Error: 502, "Bad gateway", "/graphql", ((data) (errors ((message . "Something went wrong while executing your query. This may be the result of a timeout, or it could be a GitHub bug. Please include `A948:495D:168775B:16D992A:63750568` when reporting this issue."))))
> ```

Huh! I'm not seeing that.

**Comment by cabo** [comment]
I'm only seeing it every second time I try to pull the repo state (issues, PRs) into emacs, which seems to use a graphql API.  Annoying.  This used to work well...

**Pull request merged**
