### PR TITLE
Index wild selector examples fix

### PR DESCRIPTION
**Pull request by graza**

### CODE REVIEW

**Comment by graza** [comment]
Forgive me if I'm going about this the wrong way.  I don't use GitHub a great deal.

**Review by gregsdennis — APPROVED** [review]
Nice catch.

**Review by glyn — APPROVED** [review]
Good catch - thanks!

**Comment by glyn** [comment]
> Forgive me if I'm going about this the wrong way. I don't use GitHub a great deal.

This PR is a great way to contribute.

**Pull request merged**
