### PR TITLE
Close discussion D4

### PR DESCRIPTION
**Pull request by glyn**
Here's a chance to actually have the discussion if anyone wants to.

### CODE REVIEW

**Comment by cabo** [comment]
One related question is whether the selector can use $ internally (still returning nodes within the current node).

**Comment by glyn** [comment]
> One related question is whether the selector can use $ internally (still returning nodes within the current node).

I am in favour of supporting `$` inside filter expressions as a way to access the root node of the argument, but I don't think that should block this PR as the context of the discussion seems to be which nodes are selected. As you point out, using `$` in a filter expression doesn't select the root node - it selects nodes within the current node as usual.

**Comment by gregsdennis** [comment]
I agree.  Paths like `$.foo[?(@.bar < $.baz)]` should be allowed, but wouldn't select anything that is not a descendent of `$.foo`.  Here the `$.baz` provides a basis for comparison used to select the current node `@` in the iteration.

I see no value (for an initial release anyway) in allowing selection of ancestor nodes.  If a use case and syntax for it are later defined, I'm happy to release that as a follow-up version.

**Comment by goessner** [comment]
yes ... using `$` in a logical expression is valid and does no harm.

**Review by goessner — APPROVED** [review]

**Comment by gregsdennis** [comment]
@goessner yes, but the issue at hand here is whether there is a mechanism that can select ancestor or cousin nodes.  I think we're in agreement that that there is no such mechanism.

**Review by cabo — APPROVED** [review]
Indeed, we seem to be in agreement.

**Pull request merged**
