### PR TITLE
Abnf cleanup

### LINKED ISSUE #344: Perform a full grammar review and consolidation
E.g., <https://mailarchive.ietf.org/arch/msg/jsonpath/ryGaOjcEN8MKVGuxwk4N0LbgTlI>

### PR DESCRIPTION
**Pull request by cabo**
Close #344 
(Once completed)

### CODE REVIEW

**Comment by goessner** [comment]
Erroneously commented to already closed https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/344#issuecomment-1382692603 and https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/344#issuecomment-1382693954

**Comment by cabo** [comment]
Thanks.  #344 is not yet closed; completing this #353 is meant to do that.
The triple dot bug was already fixed here in [084c822](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/353/commits/084c822cd1fa3ff418a09c4d720f8b45428d4097).
For me it doesn't matter where additional comments are made.

I wonder whether we should finish this round (fixing bugs) before doing a grand renaming.
I also would like some feedback on the names proposed...

**Review by glyn — COMMENTED** [review]
This PR looks fine to me. @cabo do you want to merge it and we can follow up with more PRs or is your intention to add more commits to this PR first?

**Comment by goessner** [comment]
well, finishing this round before going on is fine.

**Comment by cabo** [comment]
I think if we agree this we should merge it.  Next step could be the great renaming, possibly with some further testing of the grammar.  In particular, we should throw collections of JSONPath queries we can find at it.  If you have pointers, I could prepare that.

**Review by glyn — APPROVED** [review]

**Comment by glyn** [comment]
@cabo Two sources of queries:

* https://github.com/jsonpath-standard/jsonpath-compliance-test-suite/blob/main/cts.json
* https://github.com/cburgmer/json-path-comparison/tree/master/queries

**Pull request merged**
