### PR TITLE
Change title per #68

### PR DESCRIPTION
**Pull request by timbray**

### CODE REVIEW

**Review by glyn — APPROVED** [review]

**Review by gregsdennis — APPROVED** [review]

**Comment by gregsdennis** [comment]
Pro tip: edit the opening comment to include "Resolves #68" and GitHub will close the issue when this PR merges.

**Comment by timbray** [comment]
Heh, "Fixes #whatever" I think works too.  I'm in another project where you're not allowed to do that because there are designated issue-closers. Noted.

**Review by cabo — APPROVED** [review]

**Comment by glyn** [comment]
@timbray Please could you rebase this PR on `main`?

**Comment by glyn** [comment]
I've cherry-picked the fix over to https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/85.

**Comment by timbray** [comment]
Thanks!

**Pull request closed without merging**
