### PR TITLE
Delete surprising behaviour sentence

### PR DESCRIPTION
**Pull request by glyn**
Based on a comment from @timbray and the attempt to delete this sentence in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/454.

### CODE REVIEW

**Review by timbray — CHANGES_REQUESTED** [review]
I don't think the text adds any value and, in most readers, is going to lead to puzzlement and fear that they're missing something important.  

The fact that you're going to all this work to motivate a feature that isn't actually used makes me wonder why it's even in the spec.

**Comment by glyn** [comment]
> I don't think the text adds any value and, in most readers, is going to lead to puzzlement and fear that they're missing something important.

You're probably right.

> 
> The fact that you're going to all this work to motivate a feature that isn't actually used makes me wonder why it's even in the spec.

I've deleted it. I doubt we'll miss it once we've gotten over the deletion.

**Comment by cabo** [comment]
Well, the sentence points out that `value()` is not special in any way (we have discussed variants of this function).  It is just the one that fits naturally into what we have been doing elsewhere.  The sentence is true. It also provides information that may not be obvious.  So how does it not add value?  It is true that it is a note and has no normative effect, so deleting it only hurts those people who now independently have to discover this.

**Comment by glyn** [comment]
@timbray WDYT to @cabo's rationale for keeping the sentence? I can see both advantages either way.

**Comment by glyn** [comment]
> @timbray WDYT to @cabo's rationale for keeping the sentence? I can see advantages either way.

@timbray Closing. Please re-open if you feel sufficiently strongly.

**Comment by gregsdennis** [comment]
I think stating the rationale behind not having that conversion is reasonable.

**Pull request closed without merging**
