### PR TITLE
Close discussion D1

### PR DESCRIPTION
**Pull request by glyn**
Here's a chance to actually have the discussion if anyone wants to.

### CODE REVIEW

**Comment by cabo** [comment]
Well, I'm certainly ready for this model.

**Comment by gregsdennis** [comment]
I'm good with the approach described in the text.  As long as a string can be parsed as a Path, it should evaluate.  I can't see a case where processing a valid path against a value would produce an error; merely empty result sets.

This means that the only errors should be syntax errors, correct?

**Comment by glyn** [comment]
> This means that the only errors should be syntax errors, correct?

I think so.

**Comment by glyn** [comment]
May I encourage reviewers who are in favour of this PR to approve it?

**Comment by gregsdennis** [comment]
I was awaiting a bit more discussion.

**Comment by glyn** [comment]
Ok, I've requested a review from Stefan.

**Comment by goessner** [comment]
> are we ready for the error model defined here, i.e. one
> that does not have runtime errors, but only compile time errors?

Yes absolutely ... I like that clean concept a lot.

**Review by goessner — APPROVED** [review]

**Review by gregsdennis — APPROVED** [review]

**Pull request merged**
