### PR TITLE
Delete messy example

### PR DESCRIPTION
**Pull request by glyn**
Fixes https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/274

### CODE REVIEW

**Review by timbray — APPROVED** [review]

**Comment by gregsdennis** [comment]
Do we intend to replace this with anything? What is its purpose in being here?

**Comment by timbray** [comment]
The N-1 line also illustrates the point so I think it's probably OK to leave it?

**Comment by cabo** [comment]
Sorry, I didn't pay attention.
The purpose of this example was to show that escaped characters are normalized into their actual equivalents (unless there is a reason not to do so).

The messiness is a workaround for xml2rfc bugs.  I'm confident we can get these bugs fixed before this is published; otherwise we might indeed want to skip this example.

**Comment by glyn** [comment]
Why doesn't the `$["\u0061"]` example already shows that an escaped character is normalised into its actual equivalent ("a")?

**Pull request merged**
